name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install truenas_connect_utils
        run: pip install --break-system-packages --no-deps --ignore-installed .

      - name: Run tests
        run: pytest -v --disable-pytest-warnings pytest/unit
