name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:26

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install --break-system-packages --no-deps --ignore-installed .

      - name: Run tests
        run: pytest-3 -v --disable-pytest-warnings pytest/unit
